### ISSUE TITLE
Ajout de la numérotation des paragraphes en prévisualisation

### ISSUE THREAD

**Issue by mattheyje** [EcrituresNumeriques/stylo#1001]
Une évaluatrice souligne le fait que les paragraphes ne sont pas numérotés dans la prévisualisation de Stylo, et que cela pourrait être utile pour certaines pratiques.

**Comment by marviro** [comment]
C'est une très bonne idée, en effet

**Comment by marviro** [comment]
Où se trouve actuellement le template utilisé, @ggrossetie ? Je suis un peu perdu dans le code.

**Comment by davvalent** [comment]
Exemple avec CSS :

```css
article {
    counter-reset: para;
  }
article p::before {
  counter-increment: para;
  content: counter(para);
  position: absolute;
  left: -1.5em;
}
article p {
  position: relative;
}

```
