### ISSUE TITLE
Corriger les erreurs de déploiement de la documentation

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#1187]
![Image](https://github.com/user-attachments/assets/78df1eea-d530-4959-9401-440d16f6a611)

**Comment by ggrossetie** [comment]
J'ai l'impression que l'erreur vient du fait qu'on lance le déploiement de la documentation quand on ferme une pull request (et dans ce cas, le workflow se lance à partir de la branche) : 

```
Deploy Eleventy site to Pages #119: Pull request #1194 closed by thom4parisot
```

Je propose de supprimer le déclenchement sur cet évènement : 

```yaml
  # When PR is merged
  # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges
  pull_request:
    types:
      - closed
```


Sur le dépôt cité en exemple, il n'y a pas cet évènement : https://github.com/distantcam/windty/blob/main/.github/workflows/deploy.yml

```yaml
on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
```

Qu'est-ce que tu en penses ?
