### ISSUE TITLE
yaml incomplet après édition des métadonnées

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#29]
Il manque notamment la donnée `rights`.
Est ce qu'elle est oubliée lorsque le yamlEditor passe du mode auteur au mode éditeur ?

**Comment by lakonis** [comment]
par ailleurs la donnée `bibliography` est doublée (présente deux fois).

**Comment by marviro** [comment]
il manque TOUS LES CHAMPS EN DUR: Issn, éditeur etc.:
```
url_article_sp: ''
publisher: Département des littératures de langue française
prod: Sens Public
prodnum: Sens Public
diffnum: Érudit
rights: >-
  Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC
  BY-NC-SA 4.0)
issnnum: 2104-3272
journal: Sens public
director:
  - forname: Marcello
    surname: Vitali-Rosati
    gender: male
    orcid: 0000-0001-6424-3229
    viaf: ''
    foaf: ''
    isni: ''
```
Je pense qu'il faut les mettre tous éditables dans le yaml stylo.
