### ISSUE TITLE
Disparition de l'affichage des mots-clés dans l'espace métadonnées (au moment de l'édition)

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#335]
Sur les articles existants avant le déploiement du 16 mars 2021, les mots-clés ne s'affichent pas dans l'espace métadonnées, seule la langue des mots-clés est affichée.

Dites moi si vous avez besoin d'informations complémentaires @oncletom @Mogztter.

**Comment by thom4parisot** [comment]
Je constate le bug en effet.

Dans le yaml je vois : 

```yaml
keywords:
  - lang: fr
    list: édition, bac-à-sable
    list_f: édition, bac-à-sable
  - lang: en
    list: publishing, sandbox
    list_f: publishing, sandbox
```

Dans l'éditeur, je vois : 

<img width="413" alt="image" src="https://user-images.githubusercontent.com/138627/111682929-35a36400-8825-11eb-9edc-650dcda00ae3.png">

**Comment by antoinentl** [comment]
Yep c'est bien cela !

**Comment by ggrossetie** [comment]
Je pense que le format n'est pas reconnu par React JSON Schema form.
Est-ce qu'on prévoit une migration des données YAML (dans la base de données MongoDB) pour transformer:

```yaml
keywords:
  - lang: fr
    list: édition, bac-à-sable
    list_f: édition, bac-à-sable
  - lang: en
    list: publishing, sandbox
    list_f: publishing, sandbox
```

en:

```yaml
keywords:
  - lang: fr
    list_f:
      - édition
      - bac-à-sable
  - lang: en
    list_f:
      - publishing
      - sandbox
```

On peut aussi le faire au chargement de l'article mais ça ajoutera une "verrue" dans le code.
