### ISSUE TITLE
Prévisualisation cassée pour certains articles : pas d'affichage des métadonnées

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#341]
Les métadonnées ne sont pas affichées sur la prévisualisation pour certains articles (présence en fin de document) :

![Capture d’écran de 2021-03-20 11-36-44](https://user-images.githubusercontent.com/6869488/111875519-a3a87200-8970-11eb-9af9-39c9493eb345.png)

Nous ne sommes pas parvenus à déterminer pourquoi certains articles sont concernés et d'autres non :

- a priori les anciens (avant les déploiements récents) articles sont concernés et pas les nouveaux, mais tous les _anciens_ ne comportent pas cette erreur ;
- le nombre de métadonnées ne semble pas en cause (par exemple s'il manquait une donnée).

Dites comment je peux vous partager un article pour chercher une solution pour ce problème @oncletom @Mogztter

**Comment by antoinentl** [comment]
Peut-être lié à ce bug : lorsqu'on modifie le titre d'un article via le masque de saisi (le panneau latéral), le titre n'est modifié que pour `title_f` et pas pour `title` dans le yaml.

Le comportement des métadonnées pose donc plusieurs problèmes, peut-être encore en lien avec #335 ?

**Comment by thom4parisot** [comment]
Peux-tu partager avec nos comptes (`humanum@thomas.parisot.me`, pour Guillaume… peut-être son email habituel ?) un article ancien qui fonctionne, et un ancien dont les métadonnées n'apparaissent pas dans l'export ? Parce que là comme ça je ne vois pas d'erreur dans les logs de l'export, donc ça se joue ailleurs.

**Comment by thom4parisot** [comment]
Aussi, est-ce que l'attente c'est que les métadonnées _soient_ ou _ne soient pas_ affichées en fin d'article ?

**Comment by antoinentl** [comment]
Je n'arrive pas à partager d'article... Je viens de faire l'essai avec un _nouvel_ article, le bug est là. Tu peux créer un nouvel article et donner un titre pour tester.

**Comment by ggrossetie** [comment]
> Peut-être lié à ce bug : lorsqu'on modifie le titre d'un article via le masque de saisi (le panneau latéral), le titre n'est modifié que pour title_f et pas pour title dans le yaml.

`title` est "déduit" à partir de `title_f`. Autrement dit, on génère la valeur `title` à partir de `title_f` lors de l'export/prévisualisation.

Dans ta capture d'écran, on peut voir les métadonnées affichés en texte brute en bas de l'article. J'ai l'impression que les métadonnées contiennent des champs supplémentaires.

Est-ce que tu peux nous partager le lien de la page?

> Je viens de faire l'essai avec un nouvel article, le bug est là. Tu peux créer un nouvel article et donner un titre pour tester.

Est-ce que tu pourrais détailler les étapes ? Je ne reproduis pas l'anomalie:

![working](https://user-images.githubusercontent.com/333276/111876810-bfc40780-89a0-11eb-8b07-241f9e619eb2.gif)

**Comment by antoinentl** [comment]
Ok effectivement je viens de recréer un nouvel article et désormais cela fonctionne... La fonction de partage ne semble plus fonctionner de mon côté, donc voici l'identifiant d'un article qui pose problème : `60561d49b102090019adde18`

**Comment by antoinentl** [comment]
Sur les documents/articles qui posent problème, lorsqu'on modifie le titre voici ce que nous obtenons :

```
---
articleslies:
  - auteur: ''
    titre: ''
    url: ''
director:
  - foaf: ''
    forname: ''
    gender: ''
    isni: ''
    orcid: ''
    surname: ''
    viaf: ''
dossier:
  - id: ''
    title_f: ''
lang: fr
link-citations: true
nocite: '@*'
publisher: test
rights: >-
  Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC
  BY-NC-SA 4.0)
title: Titre
title_f: Titre e
translations:
  - lang: ''
    titre: ''
    url: ''
translator:
  - forname: ''
    surname: ''
---
```
Où `title` est différent de `title_f`.
