### ISSUE TITLE
Yaml Editor : nouveaux champs à rendre éditable

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#39]
Plusieurs champs ont été ajoutés au yaml par défaut de Sens Public, et plusieurs nécessitent d'être éditables dans le yaml editor. Notamment : 

```yaml
---
translator:
  - forname: ''
    surname: ''
    orcid: ''
lang: fr
orig_lang: ''
translations:
  - lang: ''
    titre: ''
    url: ''
articleslies:
  - url: ''
    titre: ''
    auteur: ''
nocite: ''
---
```
