### ISSUE TITLE
Déploiement de l'API pandoc

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#647]
Pour le moment nous utilisons un préfixe (mais à terme nous aurons un sous-domaine):

**Configuration NGINX**
```nginx
  location = /pandocapi {
    return 302 /pandocapi/;
  }

  location /pandocapi/ {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_set_header X-NginX-Proxy true;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_buffer_size          128k;
    proxy_buffers              4 256k;
    proxy_busy_buffers_size    256k;

    proxy_pass http://pandocapi/;
  }
```

**Comment by ggrossetie** [comment]
**Configuration docker-compose.yml**

```yml
  pandocapi:
    image: "davidbgk/pandoc-api:0.0.4"
    environment:
      - 'TEXINPUTS=.:/usr/pandoc-api/tmp/:'
    command: uvicorn app.main:app --workers 4 --host=0.0.0.0 --port=8000 --root-path=/pandocapi
    ports:
      - 127.0.0.1:3080:8000
```
