### ISSUE TITLE
Perte de métadonnées

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#687]
Je remarque régulièrement la perte de métadonnées renseignées dans le volet Metadata. Je dois m'y reprendre à plusieurs fois parfois pour qu'une métadonnées soient effectivement prise en compte.
Je n'ai pas l'impression que ce soit lié au fait qu'une preview soit lancée, ou au fait qu'une version soit déclarée.

Dernière épisode, j'initie les métadonnées dans un document récent (avec déjà du contenu). J'en renseigne plusieurs à la fois. Je ferme le volet, je lance une preview et toutes mes métadonnées sont perdues.

Pour tester, je remets un titre, ca marche, il est bien enregistré (la preview le présente). Mais je le perds à nouveau quelques opération plus tard.

**Comment by thom4parisot** [comment]
Tu peux donner un exemple de nom de métadonnées que tu perds ? Un avant/après du `raw` ?

**Comment by lakonis** [comment]
J'avais renseigné en premier lieu titre, date auteur, résumé mots-clés.

Je vais essayer de retrouver les raw sur les diff. Versions.

**Comment by ggrossetie** [comment]
peut être que tu avais une version sélectionnée et que tu as édité les métadonnées ? Actuellement les métadonnées ne sont pas en lecture seule quand on est sur une version. Cela donne l'impression qu'on peut mettre à jour les métadonnées mais rien ne s'enregistre.

**Comment by lakonis** [comment]
Alors, non, car après avoir perdu une fois les données, j'ai tenté de réécrire les métadonnées pour vérifier. Tenté également de comprendre s'il y avait un scénario de perte de métadonnées:
- édition uniquement des métadonnées entre deux versions
- édition des métadonnées puis du texte, ou au contraire du texte puis des métadonnées.

je n'ai pas trouvé de pattern, mais la perte s'est reproduite. Parfois sur toutes les métadonnées, parfois seulement sur un ou deux champs (sur 4 ou 5 remplis).

Ce que j'ai remarqué, c'est que les métadonnées ne bougent plus une fois que je les ai bien retrouvées soit en changeant de version, soit en réouvrant l'article depuis la liste d'article. Donc c'est comme si la perte se faisait côté client. Attention, c'est une intuition. Si je ne suis pas clair, je peux tenter de rééxpliquer.

**Comment by ggrossetie** [comment]
Je pense qu'une petite vidéo qui reproduit le problème pourrait être très utile. Sur macOS, tu peux utiliser "Capture d'écran" et sur Linux tu peux utiliser [Peek](https://github.com/phw/peek) (qui fonctionne très bien). Sur Windows, aucune idée 😉

**Comment by RochDLY** [comment]
Je relance ce fil parce que je viens d'avoir le même problème sur la métadonnée [Title] sous windows et ubuntu. Malheureusement je n'ai pas pu faire de capture (car dès lors que j'essaye la panne disparait et les metadonnées s'enregistrent par magie). Si j'arrive à la capturer je l'enferme dans une bugball !

**Comment by lakonis** [comment]
Je précise la panne (qui vient de m'arriver à nouveau sur l'article `63e285e87c2fd60013435720`:

1. je crée un article, j'édite des éléments dans le corps de texte
2. je crée une version 0.1
1. j'édite pour la première fois les métadonnées d'un article nouvellement créé : titre, sous-titre, date, langue, auteurs
3. je crée une version 0.2
4. j'édite dans le corps du texte
5. je lance une preview (tout est bon)
6. je reviens sur l'onglet Stylo, j'ouvre le volet métadonnées, et là le titre et sous-titre ont disparus.
7. je crée une version 0.3
8. je clique sur la version 0.2 : les métadonnées sont complètes
9. je clique sur la version 0.3 : les métadonnées sont complètes.
10. je reviens sur le mode édition : les métadonnées sont complètes

Donc il y a eu un pb d'affichage dans le volet metadonnées où certaines données avaient disparues. Je les ai retrouvé en versionnant. Mais.. il me semble que la dernière fois, j'ai voulu rééditer une partie des champs disparus et pour le coup les champs disparus non réédités avaient vraiment disparus..

**Comment by thom4parisot** [comment]
Merci pour la description de la mécanique 🙂 
Quand tu constates la perte des données, si tu recharges la page, est-ce qu'elles apparaissent comme attendues ?

**Comment by lakonis** [comment]
je pense à faire la manip dès que le bug se reproduit à nouveau. 

Question: si je recharge ma page, je perds ce que j'ai éventuellement écrit ? (je crois savoir que non, mais je demande confirmation :) )

**Comment by ggrossetie** [comment]
> Je précise la panne (qui vient de m'arriver à nouveau sur l'article 63e285e87c2fd60013435720:
> je crée un article, j'édite des éléments dans le corps de texte
> je crée une version 0.1
> j'édite pour la première fois les métadonnées d'un article nouvellement créé : titre, sous-titre, date, langue, auteurs
> je crée une version 0.2
> j'édite dans le corps du texte
> je lance une preview (tout est bon)
> je reviens sur l'onglet Stylo, j'ouvre le volet métadonnées, et là le titre et sous-titre ont disparus.

J'arrive bien à reproduire l'erreur, je regarde.
Si je rafraîchis sans créer la version 3, je perds mes métadonnées ! Par contre elles sont présentes sur la version 2.

**Comment by ggrossetie** [comment]
Avant de créer la version 0.2, le YAML est:

```yaml
---
articleslies:
  - auteur: ''
    titre: ''
    url: ''
date: '1986-05-10'
director:
  - foaf: ''
    forname: ''
    gender: ''
    isni: ''
    orcid: ''
    surname: ''
    viaf: ''
dossier:
  - id: ''
    title_f: ''
lang: en
link-citations: true
nocite: '@*'
rights: Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
subtitle_f: subtitle
title_f: title
translations:
  - lang: ''
    titre: ''
    url: ''
translator:
  - forname: ''
    surname: ''
---
```

Après avoir crée la version 0.2, le YAML est:

```yaml
---
bibliography: ''
title: ''
title_f: ''
surtitle: ''
subtitle: ''
subtitle_f: ''
year: ''
month: ''
day: ''
date: ''
url_article_sp: ''
publisher: ''
prod: ''
funder_name: ''
funder_id: ''
prodnum: ''
diffnum: ''
rights: >-
  Creative Commons Attribution-ShareAlike 4.0 International (CC
  BY-SA 4.0)
issnnum: ''
journal: ''
journalsubtitle: ''
journalid: ''
director:
  - forname: ''
    surname: ''
    gender: ''
    orcid: ''
    viaf: ''
    foaf: ''
    isni: ''
abstract: []
translatedTitle: []
authors: []
dossier:
  - title_f: ''
    id: ''
redacteurDossier: []
typeArticle: []
translator:
  - forname: ''
    surname: ''
lang: fr
orig_lang: ''
translations:
  - lang: ''
    titre: ''
    url: ''
articleslies:
  - url: ''
    titre: ''
    auteur: ''
reviewers: []
keyword_fr_f: ''
keyword_en_f: ''
keyword_fr: ''
keyword_en: ''
controlledKeywords: []
link-citations: true
nocite: '@*'
issueid: ''
ordseq: ''
---
```

**Comment by ggrossetie** [comment]
Il est intéressant de noter que le `yaml` et le `rawYaml` sont différents. Dans `rawYaml`, j'ai:

```yaml
---
articleslies:
  - auteur: ''
    titre: ''
    url: ''
date: '1986-05-10'
director:
  - foaf: ''
    forname: ''
    gender: ''
    isni: ''
    orcid: ''
    surname: ''
    viaf: ''
dossier:
  - id: ''
    title_f: ''
lang: en
link-citations: true
nocite: '@*'
rights: Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
subtitle_f: subtitle
title_f: title
translations:
  - lang: ''
    titre: ''
    url: ''
translator:
  - forname: ''
    surname: ''
---
```

Et quand on crée une nouvelle version, la variable `yaml` remplace le `rawYaml` et on perd les métadonnées.
