### ISSUE TITLE
Preview : superposition de la toc avec l'article lorsqu'on ouvre le volet annotation

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#907]
Bonjour! petit bug d'affichage sur la preview:

![image](https://github.com/EcrituresNumeriques/stylo/assets/9479788/922bf6c5-c343-457c-b4f8-bd69015baa80)

Il faut sans doute rendre la règle css plus robuste :

```css
  @media only screen and (max-width: 1000px)
nav {
  display: none;
}
```
