### ISSUE TITLE
Adaptations du modèle de (méta)données pour l'export (format TEI Commons Publishing en priorité)

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#940]
Voici quelques adaptations nécessaires :

- modifier `translations.titre` en `translations.title`
- modifier les titres/intitulés des champs "Traductions de"

**Comment by ggrossetie** [comment]
Le nommage a été revu complétement dans la version 3.2 quand on utilise `metadata`. Pour la rétrocompatibilité, le champ `yaml` contient les anciennes valeurs.


![Image](https://github.com/user-attachments/assets/1fdd2171-fdd2-4b05-9dc5-1e38b9befab2)


```yaml
translationOf:
  lang: en
  title: Hello World
  url: https://www.sens-public.org/articles/1781/
```

@antoinentl Est-ce que cela te convient ? Je cloture ?
